version: "3"

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  api:
    container_name: kotlin-api
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - 7000:7000
    environment:
      - REDIS_URL=redis://cache
